version: '3.8'

services:
  application:
    image: 'application:1.0.0'
    container_name: 'java-application'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://java-postgres:5432/vkProject'

  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=vkProject'