spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/vk
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml

jwt:
    secret:
        access:
            key: B6E5061FADAD40CCAEBDD0F4B3EB3DEE3F4FCE86695FA0076BA9E0A894A53140
            expiration: 99999999999
        refresh:
            key: 6cc6e57d734e612ff0c4c24aec8eef175ef34befc6c52ca73e82ba695d2c69c4
            expiration: 600